language: node_js
node_js:
- node
cache:
  directories:
  - node_modules
notifications:
  slack:
    secure: ACaBL17S3vCOEqAGp0aEh+wEFkP/C7H1NkaWU8cOCKsq1PSh8600cGsayFxJGptKa6gL+APSOZIPM1fAsTi36OG2woDhowsUMsFEgwbMYRiIvNNQciUudJdRLmlp2MvvAg+K4EJQ6bGX3qUeDP8kOt5yzudyrO1XZpOuP2OLFJPXLj+pW21gONmJGHWc+oSNzb3LpWJ6Jciyl8n8y/wMyoLioKnQ+8SwL5GAv2wITan7nCKUQ1PFQ9ASuUNWc9mHuYZvIrN6wkLxQRwPyL1e1ok2PGTE0p9M1tJAWrtLUOMFTC3KCbrfBUEfOzaDI7JP6V5h5rzVNHtcZItj+R9CPGyWSJTAFVb4lSmrUngU/TenBbqAbQTYH2JLWBj69T/AeDyNeVOSQha4uBkoLtdRCfOs3xpWZA8Bmigb1uj1z4QwpBHPEiv5XtV/dW1Gqa2zeDWgJeHBHHhpd/OrR8M/MwTnLodaU0NgomMAXa2v/Yu3PaCeoTFPbdULJvs0PcUNtv/TzOLSG0knnEzL0oHebAUtduaIoeyTLaeIcMa/vPgPXygmk/wx1KSnJDrW97AbzDDFVsHuxfBaFeAI3JMyaqW67b17HqNx2kzdt/ZqLMcDzLkdqJzN1vxryYVTmseuAtptlAe7vLrlo/8NGvcgHXUrko3dXPfrRz4Zkc6Vk7U=
